# Generated by Django 2.2.2 on 2019-06-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=1000, verbose_name='descricao'),
        ),
    ]
