# Generated by Django 2.2.2 on 2019-06-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190628_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='produto',
        ),
    ]
